import { supabase } from "@/lib/supabase";

export async function signup(
  full_name,
  email,
  password,
  otp,
  is_verified = false
) {
  try {
    // Create user with Supabase Auth
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email,
      password,
    });

    if (authError) {
      console.error("Signup failed:", authError.message);
      return "Signup Failed";
    }

    // Insert user details into 'users' table
    const { data: userData, error: userError } = await supabase
      .from("users")
      .insert([
        {
          id: authData.user.id, // Use the same ID generated by Supabase Auth
          full_name,
          email,
          password, // You might want to hash the password before storing
          otp,
          is_verified,
        },
      ]);

    if (userError) {
      console.error("Error saving user data:", userError.message);
      return "Error saving user data";
    }

    return "User registered successfully!";
  } catch (error) {
    return error;
  }
}
